### ISSUE TITLE
Expansion is inconsistent, sometimes it loads, sometimes it doesn't. Sometimes there are duplicates.

### ISSUE THREAD

**Issue by agathauy** [mrjackphil/obsidian-text-expand#10]
I noticed that Expander can be a bit inconsistent. (Kudos btw for this plugin!)
1. It won't work if there are two expanders in the same file.
2. Sometimes even if it's just alone in the file, one would have to delete the entire thing and rerun the expand trigger.
3. It tends to output duplicates. Also duplicating the ending "---" that it outputs. It also dupilcated my usual note template footer which is:

```
---
related:
```
Such that by running expander it becomes:

```
---
related:


---
related:

```

4. Here's an example of the outputs being doubled. This is from a note that just has expander in it. This happens for this case when it's rerun a 2nd time and onwards. For this case, the content of "[[00-Chapter 2]]" was changed, and it does update in the expanded notes. However, the other two unchanged files were somehow appended(?) to the end of the note.

````
```expander
{{path:Chapters/}}
[[$filename]]
$lines

---

```

[[00-Chapter 2]]
## Subsection
lalala

---

[[01-Chapter 1]]
# A section
lalala

---

[[30-Chaper 1]]
# Chapter 1

Yolo yolo yolo


|             |       |         |        |          |       |
|-------------|-------|---------|--------|----------|-------|
| da;da;;dada |       |         |        | testing  | table |
| table       | table | Testing | teable | lalalala | table |





---



---

[[01-Chapter 1]]
# A section
lalala

---

[[30-Chaper 1]]
# Chapter 1

Yolo yolo yolo


|             |       |         |        |          |       |
|-------------|-------|---------|--------|----------|-------|
| da;da;;dada |       |         |        | testing  | table |
| table       | table | Testing | teable | lalalala | table |





---



---
````

**Comment by mrjackphil** [comment]
Thanks for feedback. I definitely should work on stability for next release.

**Comment by mrjackphil** [comment]
@agathauy Release v0.7.0 has significantly improved the stability of the expander behavior. Feel free to reopen the issue if you have can recreate the issues above.
