### ISSUE TITLE
Feature Merge: Parent Name and File Path

### ISSUE THREAD

**Issue by giulianofiorotto** [mrjackphil/obsidian-text-expand#11]
Hi,

i've implemented myself two new command: $path and $parent because i had the necessity of displaying the name of the folder that contains my note;

My current organization is:
[Project name]
 - Note 1

With my implementation i can display 
|Folder|Link|
|-------|----|
|$parent| $filename |

and i get

|Folder|Link|
|-------|----|
|Project 1|[[note 1]]|

If you are intrested of merging my code (2 lines added in main.js), I would be grateful 👍 

Regards

**Comment by mrjackphil** [comment]
Sure, thanks! Just do a pull request, I'll check when will have just a little bit more time and will merge it.

**Comment by mrjackphil** [comment]
Now available in [latest release](https://github.com/mrjackphil/obsidian-text-expand/releases/latest)
