### ISSUE TITLE
Is the text-expand plugin works with the lastest version?

### ISSUE THREAD

**Issue by 1orZero** [mrjackphil/obsidian-text-expand#14]
![image](https://user-images.githubusercontent.com/53516684/100333955-2302e600-300e-11eb-8fc8-ebd4d919dff5.png)
![image](https://user-images.githubusercontent.com/53516684/100334070-43cb3b80-300e-11eb-95dc-9bad82b66493.png)

I opened the command panel and use the command but nothing is happening

**Comment by mrjackphil** [comment]
Looks like not. Looking for issue.

**Comment by mrjackphil** [comment]
Should be fixed in 0.6.0

**Comment by 1orZero** [comment]
Thanks for fixing it! Will try it today❤️
