### ISSUE TITLE
Obsidian 0.9.19

### ISSUE THREAD

**Issue by empik-foto-it** [mrjackphil/obsidian-text-expand#15]
This plugin doesn't work in new Obsidian 0,9.19.
It runs search but does not copy links to a document.

**Comment by mrjackphil** [comment]
Can't reproduce the error. Could you provide more info about the issue?
- Is there any errors in Developer's Console?
- Is it happens every time or for specific cases?
- If it's still not work for you, you can send me a little zip with minimal vault so I can reproduce the error.

**Comment by raineszm** [comment]
I'm having this same issue. I get the following error in the console when I try to use the Text {{expand}} command
```
Uncaught TypeError: Cannot read property 'map' of undefined
    at TextExpander.reformatLinks (eval at <anonymous> (app.js:1), <anonymous>:110:26)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:195:30)  
```

**Comment by psy667** [comment]
Same issue on 0.9.20

**Comment by mrjackphil** [comment]
@empik-foto-it @raineszm @psy667 Can't reproduce the error on 0.9.19-20. You can try version 0.6.1 and check is an error still there.

If it's still not work for you, you can send me a little zip with minimal vault so I can reproduce the error
