### ISSUE TITLE
Hiding the .md extension

### ISSUE THREAD

**Issue by inputsh** [mrjackphil/obsidian-text-expand#2]
Nice plugin!

It'd be nice if `.md` extension at the end of the file name would be removed. Currently if I do something like `{{tag:#example}}`, and then run the plugin, I'd get something like:

```
[[Example 1.md]]
[[Example 2.md]]
[[Example 3.md]]
[[Example 4.md]]
```

The `.md` kinda just seems redundant, and opposed to how Obsidian autofills links to other files.

**Comment by mrjackphil** [comment]
@inputsh Hi, should be fixed in new version. Also, you can check template feature if you'll ever will need an extension in your file list :)

**Comment by inputsh** [comment]
Works flawlessly! Thanks!
