### ISSUE TITLE
Feature Request: Copy Line That In Search Results

### ISSUE THREAD

**Issue by Quorafind** [mrjackphil/obsidian-text-expand#24]
For example:

I have a line("One apple a day") contains "one", I use {{one}} to trigger text {{expand}}. And then it will output the line of "one"

```
One apple a day
```

**Comment by mrjackphil** [comment]
@Quorafind Hi. What if there are several lines that contain that text? Would you expect to show all search results in a document?

**Comment by Quorafind** [comment]
@mrjackphil it would be nice that have an similar option like $matchline,  and the $matchline:10 will give us the first 10 match lines.

**Comment by mrjackphil** [comment]
Now we can extract the matched text using `$match` sequence. Is it helpful?

**Comment by Quorafind** [comment]
Oh, if it is possible to return the line contains the text(or block?) rather than the search query itself?

**Comment by Quorafind** [comment]
OK, by using regex: `/^(.*)string(.*)\n/`. I finally did it! But it will be nice that make $matchline available 😎

**Comment by fred1357944** [comment]
> OK, by using regex: `/^(.*)string(.*)\n/`. I finally did it! But it will be nice that make $matchline available 😎

can you show us how to do that? 🚀

**Comment by brozena** [comment]
+1!

This would be very useful.

**Comment by mrjackphil** [comment]
Added `$matchline` sequence in `0.10.0`.
Also you can use:

```bash
$matchline:2         #return 2 lines before and 2 line after matched line
$matchline:+2        #return 2 lines after matched line
$matchline:-2        #retrun 2 lines before matched line
```

**Comment by mrjackphil** [comment]
`$searchresult` returns exactly what you can see in Obsidian's search panel.
