### ISSUE TITLE
List of links to line which match a pattern

### ISSUE THREAD

**Issue by dariuszkowalski-com** [mrjackphil/obsidian-text-expand#3]
I have found this plugin as a very useful tool.

During a day I am adding tags to notes which I like to discuss with someone else
Before a meeting, I just filter out them all. 

Now I have got a list of files where I have noted something.

Usually, I pass through that files and add a link to a paragraph by using `^` char and selecting a line with appropriate information.

It would be nice to have it done in automatic form and which provide results like this:

-  [[ LINK TO A FILE^line of existens of pattern ]]

Regards

**Comment by mrjackphil** [comment]
@dariuszkowalski-com Hi, added template feature lately. Please tell if it can help you with your workflow,

**Comment by dariuszkowalski-com** [comment]
To visualize what I am think. There is a image:

![image](https://user-images.githubusercontent.com/37656900/99520089-f8bc8300-2992-11eb-9390-4f00002757b7.png)

After a search Obsidian show exacly a list of all places were pattern match.

I Would like to get list of links to this items 

[[ LINK TO A FILE^line of existens of pattern ]]

**Comment by mrjackphil** [comment]
@dariuszkowalski-com So making a special sequence something like $found which should return a found text should do the trick, right? 

So with template feature we could do
```
{{SEARCH}}
[[$filename^$found]]
```

**Comment by dariuszkowalski-com** [comment]
it could return a paragraph where pattern was found. I can then add 

`![[$filename^$found]] `

and get a content. In my case it will be set of lines with a tasks which I put accross my files / daily notes / contact reports or other  files:

```
-[ ] #TAG Something1 to do 
-[ ] #TAG Something2 to do 
-[ ] #TAG Something3 to do 
-[ ] #TAG Something4 to do 

```

**Comment by mrjackphil** [comment]
@dariuszkowalski-com Currently we can extract the matching content using `$match` sequence and heading which has matching content `$match:header`. Would it be helpful?

Also, we can extract block by `$block` sequence so you have tasks like
```
- [ ] #TAG Something to do ^task1 
- [ ] #TAG Something to do ^task2
```

it should help you to extract that.

**Comment by mrjackphil** [comment]
I think what latest updates can cover this issue. If there any additions - feel free to reopen the issue or create another one.
