### ISSUE TITLE
Extra New Lines in template output

### ISSUE THREAD

**Issue by ProbablePrime** [mrjackphil/obsidian-text-expand#30]
The current template parsing logic appears to add extra, unwanted new lines to the output.

You can see this occurring here: https://i.probableprime.co.uk/210318-4RbgHzo5XwaEwNOmfw9R.mp4

I had a look through the code and it appears too man \n's are being added: https://github.com/mrjackphil/obsidian-text-expand/blob/master/main.ts#L116-L126

In the highlighed lines, each item is first formatted with an added \n and then the resultant array is joined with \n.

**Comment by mrjackphil** [comment]
It seems I overlooked this one. Will fix this as soon as will be available.

**Comment by mrjackphil** [comment]
Should be fixed in the 0.7.3 plugin release.

**Comment by denchuku** [comment]
Thanks a lot!
