### ISSUE TITLE
Feature Request: Ignore Frontmatter and empty line for $lines-sequence

### ISSUE THREAD

**Issue by denchuku** [mrjackphil/obsidian-text-expand#32]
### Background
I often use text-expand to create TOC lists:

    ```expander
    tag:#foo
    - [[$filename]]
    ```

This produces a list as expected:

```
- [[foo-a]]
- [[foo-b]]
- [[foo-c]]
 ```

### Issue when including content
What I would like to have is some sort of summary by including the first few letters / the first line to the list so that it renders like this:

```
- [[foo-a]] foo bar a line
- [[foo-b]] foo bar b line
- [[foo-c]] foo bar c line
```
Assume this for generating it:

    ```expander
    tag:#foo
    - [[$filename]] $lines:1
    ```
This currently produces the following output:

```
- [[foo-a]] ---
- [[foo-b]] ---
- [[foo-c]] ---
```

The reason is that most of my files contains YAML frontmatter like this:

```
---
tags: ["foo"]
---

foo bar a line
more lines ...
```

### Feature Request

It would be great to have something similar to `$lines:1` but which:
- ignores yaml frontmatter
- ignores empty line at the start of the document (so that it starts at the first non-empty line after the frontmatter)

**Comment by mrjackphil** [comment]
Good catch. It's definitely should be fixed.

**Comment by mrjackphil** [comment]
@denchuku Should be fixed in the latest release. Thanks for the request!

**Comment by denchuku** [comment]
Wow, that was fast! Thanks!
It is working like a charm! 

FYI: I discovered a bug and made a new issue for that - hope that is okay: https://github.com/mrjackphil/obsidian-text-expand/issues/34
