### ISSUE TITLE
error in plugin descriptor

### ISSUE THREAD

**Issue by lwb52** [mrjackphil/obsidian-text-expand#33]
Title/Descriptor of plugin reads:
”link…in founded files”—
should be ”link…in found files” or maybe ”located files”
Thanks :^)

**Comment by mrjackphil** [comment]
Thanks! English is not my native language so sometimes I do silly mistakes 😄

**Comment by mrjackphil** [comment]
Fixed in the latest release. Thanks, @lwb52!

**Comment by lwb52** [comment]
NO WORRIES—just blessings for your hard work🙏🏻👍🏻
