### ISSUE TITLE
$header:### HEADER special sequence not working

### ISSUE THREAD

**Issue by muness** [mrjackphil/obsidian-text-expand#35]
I can't get the `$header:<...>` special sequence working.

To reproduce, I created a `hello world` file:

```
## Plugins for Obsidian
- test
- xxx

```

The expander script:

```expander
"## Plugins for Obsidian" [[$filename]]
$header:"## Plugins for Obsidian"
```

The result was

```
[[hello world]]
$header:"## Plugins for Obsidian"
```

I tried several other permutations without any luck.

**Comment by mrjackphil** [comment]
@muness Should be fixed in latest release. 
Feel free to reopen the issue if it still happened.

**Comment by muness** [comment]
Thanks, confirmed this works now. Note that the syntax indicated in the README, `$header:"## Plugins for Obsidian"` doesn't work, but `$header:## Plugins for Obsidian` does. Maybe update the README?

Also, I [noticed](https://github.com/mrjackphil/obsidian-text-expand/blob/9360dcafebfe922158ca5d00fd5b1309b5436a54/main.ts#L65) that you're returning the line that includes the header for matched ranges:

```
return [heads[i].line, heads[i + 1]?.line]
```

Any way to pass a parameter to skip the header itself?, that is have this behavior:

```
return [heads[i].line + 1, heads[i + 1]?.line]
```

For matched ranges, I already know the header and if I want it in the output could put it in the template.

Sorry about adding this here, let me know if you prefer a new issue or comms in the discord plugins channel, say.

Thanks again!

**Comment by mrjackphil** [comment]
@muness Just open a new issue here on GitHub. Thanks. 

I'm thinking about redoing some functionality to make it more flexible to use.
