### ISSUE TITLE
Update Error

### ISSUE THREAD

**Issue by Quorafind** [mrjackphil/obsidian-text-expand#36]
It seems like the update URL should contain `v0.8.1` rather than `0.8.1`

**Comment by mrjackphil** [comment]
@Quorafind Try to update to the latest 0.8.3 release, please. I accidentally created an empty tag without files.

**Comment by Quorafind** [comment]
@mrjackphil cannot download now, I would wait 3 hours to see if I could update the plugin to 0.8.2

**Comment by mrjackphil** [comment]
@Quorafind Forgot to do `git push`... Sorry. Should work now.
