### ISSUE TITLE
Specify a folder or tag not to be reflected in the query results

### ISSUE THREAD

**Issue by EhuddR** [mrjackphil/obsidian-text-expand#39]
Hi! First of all I have been using text expander since October or November last year and it has been great. I would, however, like to request an enhancement that I think would be very valuable. When we specify a search in expander it reflects all the files that have a specific tag, but, it would be very useful to be able to tell expander; Ok! pull all the files with the tag #foo but not the ones in this folder for example Templates. I hope it makes sense.

Anyway, thank you very much for this plugin 

Regards.

**Comment by mrjackphil** [comment]
@EhuddR Hi! But you already can exclude results using Obsidian's search query

    ```expander
    #book -path:Templates
    ```
should file all `#book` files but exclude the Templates folder and

    ```expander
    tag:#book -tag:#read
    ```
should find all files with tag `#book` but which doesn't have tag `#read` in it.

It uses standard Obsidian search functionality so you can read more about it [here](https://help.obsidian.md/Plugins/Search)

**Comment by EhuddR** [comment]
Ah! thank you very much, I didn't know it worked as well as the search inside obsidian. It would be very valuable to add this information to the plugin documentation.
