### ISSUE TITLE
Non-ASCII YAML field names in $frontmatter:NAME macro

### ISSUE THREAD

**Issue by alexgeirby** [mrjackphil/obsidian-text-expand#40]
Hi

I try to output value of frontmatter parameter named `Категория`, but it doesnt recognized as `\$frontmatter` macro due to `[a-zA-Z0-9_-]+` regexp...

For Russian language changing the regexp to `A-Za-z0-9а-яА-Я_` works for me. But maybe more generic and elegant solution exists?

**Comment by calpa** [comment]
Same here, my frontmatter parameter is 地區, which is a chinese name.

**Comment by mrjackphil** [comment]
Thanks for the issue. I'll check the the current implementation.
