### ISSUE TITLE
Feature Request: special sequence for file counter

### ISSUE THREAD

**Issue by alexgeirby** [mrjackphil/obsidian-text-expand#42]
I would like to ask you to implement a $counter variable that will expand to a file counter in current search 

My use case: I have a folder with small files (notes, tasks,...), first line of each file is interpreted as a note title.

With the requested function, I should be able to create a compound document with multi-level numbered headers using something like this:

    # Undone tasks for active projects
    
    ## 1. Project one
    ```expander
    path:TasksFolder tag:#Projects/ProjectOne tag:#State/ToDo
    ### 1.$counter $lines
    ```
 
    ## 2. Project two
    ```expander
    path:TasksFolder tag:#Projects/ProjectTwo tag:#State/ToDo
    ### 2.$counter $lines
    ```
    ...

**Comment by mrjackphil** [comment]
@alexgeirby Thanks for the feature request. Should be easy to implement. Will try to find some time to do this.

**Comment by alexgeirby** [comment]
Ээх.... Придется, видимо, самому учить TS/JS на старости лет...

**Comment by mrjackphil** [comment]
@alexgeirby Try `$count`. It was added in 0.9.2
