### ISSUE TITLE
$blocks result show up as (result) instead [result]

### ISSUE THREAD

**Issue by trungng2006** [mrjackphil/obsidian-text-expand#44]
I requested the plugin to return block. The link is wrapped with round bracket instead of square bracket.
![image](https://user-images.githubusercontent.com/71961905/123747050-fb963380-d8e4-11eb-93f1-d5f9c25a3e59.png)

**Comment by mrjackphil** [comment]
I think I made it to be part of other sequence. Currently you can do the markdown link. 

```
![$title]($blocks)
```

I might change the blocks logic in the future when I'll put my hands on it.

**Comment by trungng2006** [comment]
I will note down to use with markdown link. Thank you !

**Comment by mrjackphil** [comment]
@trungng2006 The behaviour was changed as you expected previously. 
So you should redone `![$title]($blocks)` to just `!$blocks`

**Comment by trungng2006** [comment]
Thank you so much!!!
