### ISSUE TITLE
[Feature Request] Human readable create time

### ISSUE THREAD

**Issue by Creling** [mrjackphil/obsidian-text-expand#47]
Hello, Is it any way to get a hummin readable create time or is it possible to add some format functions for `$created` ? Currently `$created` is not readable :(

**Comment by mrjackphil** [comment]
@Creling Added in 0.9.2:
`$created:format` -> `2021-07-22T06:21:34.556Z`
`$created:format:date` -> `2021-07-22`
`$created:format:time` -> `06:21:34`
