### ISSUE TITLE
Templating feature will not work if the block is on the first line

### ISSUE THREAD

**Issue by athiwatc** [mrjackphil/obsidian-text-expand#5]
If I have ````expander` on the first line of the document. Non of the templating feature will work.

**Comment by dariuszkowalski-com** [comment]
I have got the same bug.

When I put a filter with formating at the beginning of a file e.g:

```expander
{{ #F2F-PH✅ }}
- [[$filename]]
```

after run it is  changed to:
```expander
{{ #F2F-PH✅ }}
```

it means that all formatings are deleted.  `- [[$filename]]`  is removed

This is a bug - version 0.5.1

**Comment by mrjackphil** [comment]
Should be fixed in 0.5.2
