### ISSUE TITLE
Feature Request: retrieve content of blocks

### ISSUE THREAD

**Issue by chrisgrieser** [mrjackphil/obsidian-text-expand#50]
Thanks for the plugin!

Right now, we can retrieve block ids, and we can retrieve note content. Is it possible to retrieve content of blocks as well? Like specifically *only the blocks* that match a search.

```
block:(#test1)
$blockcontent
```

This could, for example, only retrieve the *blocks* that have the tag `#test1`.

**Comment by quowarranto** [comment]
Second this request. This is the use case that led me to this plugin.

**Comment by kabo1234** [comment]
+1 for this!

and even better if the blocks could be retrieved as embeds (rather than copied) or as text+link (eg [[source]]. That way there would be a discernible link to where the block came from.

**Comment by SenseiBas** [comment]
Thank you so much for this plugin: I would love to see this working with headers as well:
[[mynote#headercontent]]
I love the pasting in this note because I can now use it to publish the embed as html

**Comment by mrjackphil** [comment]
@chrisgrieser You can try to use `$matchline` which will return the matched line.

**Comment by mrjackphil** [comment]
So, currently you can use:
`$matchline` to get matched line. If you search for `block:` it will retrieve the content of the block.
`$blocks` which will return link to the blocks
`!$blocks` which will return embeds for blocks

If there are still issues with it - please, reopen the issue.
