### ISSUE TITLE
Return to blocks function with garbled code

### ISSUE THREAD

**Issue by wslldsdhii** [mrjackphil/obsidian-text-expand#52]
`$blocks` ：Chinese is not supported

![p1](https://raw.githubusercontent.com/wslldsdhii/picgo/main/img/img%E6%88%AA%E5%B1%8F2021-09-22%20%E4%B8%8B%E5%8D%881.40.37.png)

![p2](https://raw.githubusercontent.com/wslldsdhii/picgo/main/img/img%E6%88%AA%E5%B1%8F2021-09-22%20%E4%B8%8B%E5%8D%881.40.58.png)

**Comment by mrjackphil** [comment]
@wslldsdhii The behaviour of the `$blocks` sequence was changed. It should fix the bug.
Reopen the issue if there any problems with.
