### ISSUE TITLE
[ Bug ] Expand query not found

### ISSUE THREAD

**Issue by Armagedoom** [mrjackphil/obsidian-text-expand#53]
Hello:

I'm trying to use the plugin but I get the same answer, "Expand query not found", regardless using the examples provided:

![image](https://user-images.githubusercontent.com/4046326/135596409-b1c9d499-9d66-45a5-a008-e5638548874d.png)
(And any other thing I could try got me the same result)

What could I try to fix this? Thank you!

**Comment by mrjackphil** [comment]
@Armagedoom Hi. Already got that issue. I hope will have some time this weekend to fix this.

**Comment by Armagedoom** [comment]
Turns out if a parent folder or the current folder of the note has emojis on it, the plugin wont work.
Tested without emojis in the folder names and it works.
This bug affects also the dataview plugin.

**Comment by Armagedoom** [comment]
> @Armagedoom Hi. Already got that issue. I hope will have some time this weekend to fix this.

Sorry for that, thanks again!

**Comment by mrjackphil** [comment]
Thanks for details. And for creating and issue!

**Comment by mrjackphil** [comment]
Can't reproduce the bug anymore. If there any related problems - please, reopen the issue.
