### ISSUE TITLE
[Bug] Cannot limit search to file names

### ISSUE THREAD

**Issue by WyldKard** [mrjackphil/obsidian-text-expand#55]
The plugin descriptions says the plugin, "will search files using Obsidian search functionality..." See: https://help.obsidian.md/Plugins/Search

However, when using the query, "file:(examplequery)", nothing is returned, even though I have filenames that include "examplequery".

**Comment by WyldKard** [comment]
Played around with this a bit more and it seems I forgot to include the following after my query, so it was embedding the attachments:

```
- [[$filename]]
```

Works now, thank you!

**Comment by mrjackphil** [comment]
Glad it worked for you!
