### ISSUE TITLE
[Problem] text expansion is slow

### ISSUE THREAD

**Issue by Dahlai** [mrjackphil/obsidian-text-expand#58]
Hi,
I'm considering moving my note taking setup to Obsidian. So far, I found your plugin invaluable. 
However, running the expansion command is a test vault with just a handful of entries takes ~3-5 seconds. 
Is that to be expected or is something wrong on my end?

Thanks a lot for the info.

Cheers

**Comment by mrjackphil** [comment]
@Dahlai Hi. 

You can check the delay option in plugin settings menu. 

By default it has 1,5 sec before parsing search results and put the values.

**Comment by Dahlai** [comment]
Thanks for the quick reply. 
I set it to the minimum value of 1000 ms. It seems to improve the situation, but is there any reason why it can't be any lower than this?

**Comment by mrjackphil** [comment]
Reduced the minimum value for option to 100ms. You can play around with values.
