### ISSUE TITLE
[BUG] Text expand is not working with Obsidian 0.13.14

### ISSUE THREAD

**Issue by andrezgz** [mrjackphil/obsidian-text-expand#59]
Hello,

This is happening with several plugins nowadays, since Obsidian has been updated to CM6.

When I execute the "expand" command, the previous results are removed, the search is done with the parameters but the new results are not pasted into the editor.

Hope you get the time to fix it, since it's a great feature for Obsidian!

**Comment by tumber43** [comment]
Much like andrezgz mentioned, with the last couple Obsidian versions, text expand produces a Null result. I updated to the latest Obsidian installer with a fresh download, and same result. I'm on Version 13.19. I tried disabling all other 3rd party plugins, same result... I tried using the Legacy Editor, same result. I haven't ruled out a cache issue since the legacy editor change.

**Comment by imeed166** [comment]
+1 for this

**Comment by Masktial** [comment]
+1

**Comment by tinainsz** [comment]
+1

**Comment by chenba0** [comment]
+1

**Comment by mrjackphil** [comment]
Just for you to know: fixing the plugin is on my list. Need to spend time figuring out how CM6 works and what changed. 

Also, the most complex task is time management. 

I changed my job from doing frontend. Now I do team management. Need some time to gain experience in new profession and regulate processes in the team. 

And will have a second baby, soon.

I hope I will handle all excuses I have to bring working versions of my plugins.

**Comment by andrezgz** [comment]
I do understand your life/work pressures and priorities, @mrjackphil. You do this for pleasure and it doesn't pay your monthly bills, as you say.

The CM6 migration broke a lot of plugins and put maintainers in an awkward position. I've applied monkey patches on a few other plugins and shared them to build the definitive solution. I'll try to do the same with Text Expand.

**Comment by andrezgz** [comment]
Today, when I executed the "expand" command, it worked perfectly. The reason? The "side dock" containing the Search pane was **expanded**. It seems that every time I tried it in the past, it was collapsed. In that moment, the side-dock is expanded and collapsed quickly by the "expand" command and results are not pasted... (sometimes, some results are pasted, not all of them)

I immediately remembered reading something about "the search not running in background" in one of the Obsidian Release announcements (I check them thoroughly). Went to the forum and [found it](https://forum.obsidian.md/t/obsidian-release-v0-13-7-insider-build/28061):

> **Improvements**
> - Global search panes will no longer continuously run in the background when the pane is not in view.

So the mistery is solved. In order to bypass the issue the side dock containing the Search pane must be expanded **before** executing the "expand" command.

Don't know if there will be a definitive solution. Maybe forcing the expansion of the Search pane (like pressing `Ctrl+Shift+F` does) when the "expand" command is executed?

**Comment by QuaCKeReD** [comment]
Similar issue, still 😟

I found the search pane being open fixing the run of the search by mistake

But, when I run the expand, I now get an error under each file returned, stating that a section (that isnt detailed or requested), cannot be found in the the current file;
![CleanShot 20220317 115611 bKOXcM84](https://user-images.githubusercontent.com/2767970/158803597-30a8eb15-73bb-468c-abbb-4a14879845a4.png)

**Comment by QuaCKeReD** [comment]
which it seems is related to this;

![CleanShot 20220317 120450 7MnYE3gR](https://user-images.githubusercontent.com/2767970/158804883-9f1fa8be-6baf-4402-92c2-7106a86aea8a.png)

The header link it is using is just a [[header]], not a [[file#header]]

**Comment by QuaCKeReD** [comment]
Sorry for delay, but solution to my issue is to change output from

`!$header:appd/ps/hsbc/wsit/dsp`

to 

`![[$filename]]$header:appd/ps/hsbc/wsit/dsp`

**Comment by QuaCKeReD** [comment]
The above issue seems fixed in latest release 😀
