### ISSUE TITLE
No more list type?

### ISSUE THREAD

**Issue by mafsi** [mrjackphil/obsidian-text-expand#6]
Does the new version removed the ability to have results as list? I see only one command pressing CTRL+P . I remember more.

**Comment by mrjackphil** [comment]
Now you can use template feature to do the list. 

    ```extender
    {{Search}}
    -[[$filename]]
    ```

**Comment by mafsi** [comment]
Not working at all
I took this from info page and replace expander with my text.
Going back 2 versions. Sorry!
```
```expander
{{Expander}}
^|Filename|Content|
^|---|---|
|$filename|$content|
```

![expander](https://user-images.githubusercontent.com/61430691/98984594-14ef9880-252b-11eb-89ff-d22b02618fca.png)

**Comment by mrjackphil** [comment]
There is a typo. I'll fix it soon.
 
    ```expander
    {{Expander}}
    ^|Filename|Content|
    ^|---|---|
    |$filename|$lines|
    ```

should do the trick

**Comment by mrjackphil** [comment]
@mafsi Latest release (0.7.0) added the ability to set up a default template (which is a list now) and behavior stability was improved. Feel free to reopen the issue (or create another) if you have any problems with it.
