### ISSUE TITLE
Bug: $header: Will render link and instead of the block content

### ISSUE THREAD

**Issue by SenseiBas** [mrjackphil/obsidian-text-expand#60]
![image](https://user-images.githubusercontent.com/97248289/148735161-724a2302-4e59-4eb6-b43c-a9cfb03bdd95.png)

$header: Will render link and instead of the block content
I believe it should extract the block content of this header

**Comment by calpa** [comment]
Content is expected, but currently link is extracted...

**Comment by QuaCKeReD** [comment]
for content, you need to transclude the header, with '!' prefix

`!$header:#### level 1`

**Comment by mrjackphil** [comment]
Changed the README file. Now link is an expected behaviour.
