### ISSUE TITLE
Not compatible with blockquote syntax

### ISSUE THREAD

**Issue by zcysxy** [mrjackphil/obsidian-text-expand#65]
I want to use the plugin with Obsidian callouts, which use the blockquote syntax `>`. However, Text Expand use this syntax as a footer. Is there a way to make `>` a literal symbol?

My code:

```expander
-path:"templates" "sup:: [[Inbox]]"
^> [!content]
> ![[$filename]]
>
```

Expected output:

```markdown
> [!content]
> ![[file1]]
>
> ![[file2]]
```

Also, sometimes I want a blank line between links, but blank lines in the code block are not recognized by Text Expand.

**Comment by mrjackphil** [comment]
@zcysxy Just added ability to change prefixes in settings menu. It lands in **0.10.6** version. 
So you can setup your own prefixes for header and footer section. 
Reopen the issue if there any problems with it.
