### ISSUE TITLE
Enhancement: Make expander revert any changes after completion

### ISSUE THREAD

**Issue by QuaCKeReD** [mrjackphil/obsidian-text-expand#66]
In v0.10.8, the search tab is now opened automatically when expander triggers (understand this is now required since background searches aren't allowed anymore) - great news!!!

However, is it possible for expander to take status of active tab and search field entries BEFORE doing its work, and reverting things back to how they were once it has finished?

**Comment by mrjackphil** [comment]
Should be fixed in 0.11.2
