### ISSUE TITLE
Command to expand all blocks globally

### ISSUE THREAD

**Issue by NomarCub** [mrjackphil/obsidian-text-expand#7]
It would be nice to only issue one command to update all existing expand blocks in all files.
You could maintain all indexes and whatnot this way.
Maybe even expose it in a way so that other plugins can use it, for example to update all expand blocks before a git commit.

**Comment by dariuszkowalski-com** [comment]
+1

**Comment by HEmile** [comment]
Probably hard to do this right now, as the plugin relies on the search functionality to run everything.

**Comment by mrjackphil** [comment]
@HEmile is right. And I'm afraid it's a little bit out of the scope right now... Expander a little inconsistent right now, so expanding all files can make a lot of harm. 

Maybe I'll add something expanding for all opened files (or even for all files) but it'll be not earlier than expanding all blocks in a single file.

**Comment by mrjackphil** [comment]
@NomarCub I think expanding all existing expand blocks are a little bit out of scope. But I just added "Expand all in file" functionality. I hope it helps. Feel free to reopen the issue if someone has ideas on how can we handle this.
