### ISSUE TITLE
[Feature Request] Get a specific line of a file?

### ISSUE THREAD

**Issue by EhuddR** [mrjackphil/obsidian-text-expand#73]
Hi!
I would like to know if you can get as a search result a specific line of a note. At the moment the `$line` argument returns the entire contents of the note, likewise, using `$lines:10` returns the first 10 lines of the file. It would be helpful if you could get a specific line using something like `$line:9:9` so that you get as result the line 9 of the file. I tend to take a lot of notes with dashes as points of interest and it would be great to be able to quickly access a specific line.

![image](https://user-images.githubusercontent.com/78237982/175247251-cb280324-af88-4139-9999-9fe8315ad312.png)

Thanks.

**Comment by mrjackphil** [comment]
Hi @EhuddR. While you can't do that by sequences you can do that using eta template.

```
file:FILENAME
<% it.files.forEach(file => { %>
<%= file.content.split('\n')[8] %>
<% }) %>

**Comment by mrjackphil** [comment]
Anyone feel free to reopen the issue if there are still enough cases for this feature.
