### ISSUE TITLE
[feature request]Add some basic replacement

### ISSUE THREAD

**Issue by dentistfrankchen** [mrjackphil/obsidian-text-expand#76]
So far this plugin has shown to be very great. However, I hope you can add some replacement for it.
For example I get:
1.yyy*
2.uii*
…
I hope I can replace all * with blank since I do not want them. Also, this feature can be used to change format.

Hope it can look like:
```expander
replace: *
with: 
```

**Comment by dentistfrankchen** [comment]
Also I want to point out that this is for the result, not for the original place.

**Comment by mrjackphil** [comment]
Feel free to reopen this issue if there are more questions!
