### ISSUE TITLE
Command to expand all {{search}} in the file

### ISSUE THREAD

**Issue by dariuszkowalski-com** [mrjackphil/obsidian-text-expand#8]
I would like to have a command (assignable to a short key) which will expand all places in an opened file at once.

**Comment by HEmile** [comment]
+1 on this. I have a template with 6 searches, would be great if I could run these in sequence.

**Comment by mrjackphil** [comment]
@dariuszkowalski-com @HEmile I'm late to the party, guys. But I just added this functionality for the 0.7.5 release.
