### ISSUE TITLE
Issue: Is this plugin being maintained any more?

### ISSUE THREAD

**Issue by spiritualgeek** [mrjackphil/obsidian-text-expand#85]
Hi,

I would like to know if this plugin is abandoned?

I've started using is and just popped in to check something in the docs, and I'm worried that it seems inactive?

Thanks

**Comment by mrjackphil** [comment]
@spiritualgeek 

Kind of. It's hard to find time for it. While I can accept PR (there is one I still can't find for) but can't actively maintain it. 

While I still hope what I'll find some time for it but it still didn't happen.

**Comment by spiritualgeek** [comment]
Thank you for your honesty. I really hope you find a bit of time because I've decided to use it anyway. :)

**Comment by spiritualgeek** [comment]
I'm still using the plugin and for now, it still works. Hopefully, the author finds some time to keep it alive

**Comment by spiritualgeek** [comment]
Hi @mrjackphil - I just want you to know that I consider your plugin in my top 10 list of most useful plugins 

I hope this is motivation enough for you to continue :)
