### ISSUE TITLE
Expand query not found

### ISSUE THREAD

**Issue by MelodyDuplaix** [mrjackphil/obsidian-text-expand#87]
When I want to expand a query, no matter what I put in the search, and no matter whether I use the button created by the code block, or the command, I get an error saying "Expand query not found". Does this plugin still work?

**Comment by mrjackphil** [comment]
@MelodyDuplaix I just checked. It works on latest version of Obsidian in sandbox enrironment. 
Can you provide more detailed example of usage?

**Comment by MelodyDuplaix** [comment]
I've just tried again, after uninstalling and reinstalling several times. And it actually works now. Thanks for your response
